# Generated by Django 5.0.6 on 2024-05-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Huddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomID', models.CharField(default='', max_length=12, unique=True)),
                ('host', models.CharField(max_length=55, unique=True)),
                ('guest_permit', models.BooleanField(default=False)),
                ('skip_votes', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
